
import 'package:firstapp/models/data.dart';
import 'package:firstapp/first_cubit_state.dart';
import 'package:bloc/bloc.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'network/remote/Dio_helper.dart';
// v1/timingsByCity?city=egypt&country=cairo&method=4'


// url 2dem :'http://api.alquran.cloud/v1/surah'
class FirstCubit extends Cubit<FirstCubitState> {
  FirstCubit() : super(InitialState());

  static FirstCubit get(context) => BlocProvider.of(context);
  Autogenerated? list;
  void GetData() {
    DioHelper.getData(
      url: 'v1/timingsByCity',
      query: {
        'city': 'egypt',
        'country':'cairo',
        'method':'4',
      },
    ).then((value) {
     print(value.data);
      print("tmmm");
      list=Autogenerated.fromJson(value.data,);
     print( list!.data!.meta!.timezone);
      emit(GetDataQuranSuccessState(),);
    }).catchError((error) {
      print(
        error.toString(),
      );
      print("errror here cubit");
      emit(GetDataQuranErrorState(),);
    });
  }


}
